---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
    allow:
      - dependency-name: "endroid/qr-code"
      - dependency-name: "ircmaxell/password-compat"
      - dependency-name: "mopa/bootstrap-bundle"
      - dependency-name: "nelmio/security-bundle"
      - dependency-name: "pear/crypt_gpg"
      - dependency-name: "ramsey/uuid"
      - dependency-name: "scheb/*"
      - dependency-name: "sonata-project/*"
      - dependency-name: "tuupola/base32"
    groups:
      php-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
