# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/5.x/configuration.html
scheb_two_factor:
    # Google Authenticator config
    totp:
        enabled: true
        server_name: "%env(APP_DOMAIN)%"
        issuer: "%env(PROJECT_NAME)%"
        template: Security/2fa_form.html.twig
        parameters:
            image: "%env(PROJECT_LOGO_URL)%"

    # The security token classes, which trigger two-factor authentication.
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        # If you're using guard-based authentication, you have to use this one:
        # - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
        # If you're using authenticator-based security (introduced in Symfony 5.1), you have to use this one:
        # - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
