version: '3.8'

services:
  mysql:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: mail
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mail
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
