App\Entity\Alias:
    properties:
        source:
            - NotNull: ~
            - Email:
                mode: strict
            - App\Validator\Constraints\EmailAddress: { groups: [unique] }
            - App\Validator\Constraints\EmailLength:
                minLength: 3
                maxLength: 24

App\Entity\User:
    properties:
        email:
            - NotNull: ~
            - Email: ~
        roles:
            - NotNull: ~
            - NotBlank: ~
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~
            - NotCompromisedPassword:
                skipOnError: true
        domain:
            - Valid: ~
    constraints:
        - App\Validator\Constraints\EmailDomain: ~

App\Form\Model\Registration:
    properties:
        email:
            - Email:
                mode: strict
                message: form.invalid-email
            - App\Validator\Constraints\EmailAddress: ~
            - App\Validator\Constraints\EmailLength:
                minLength: 3
                maxLength: 32
        voucher:
            - App\Validator\Constraints\Voucher:
                exists: true
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~
            - NotCompromisedPassword:
                skipOnError: true

App\Form\Model\RecoveryTokenAck:
    properties:
        ack:
            - NotBlank:
                message: form.registration-recovery-token-noack

App\Form\Model\PasswordChange:
    properties:
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~
            - NotCompromisedPassword:
                skipOnError: true

    constraints:
        - App\Validator\Constraints\PasswordChangeConstraint: ~

App\Form\Model\PlainPassword:
    properties:
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~
            - NotCompromisedPassword:
                skipOnError: true

App\Form\Model\Delete:
    properties:
        password:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: form.wrong-password

App\Form\Model\RecoveryToken:
    properties:
        password:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: form.wrong-password

App\Form\Model\RecoveryProcess:
    properties:
        email:
            - Email:
                  mode: strict
        recoveryToken:
            - Uuid:
                message: form.invalid-token

App\Form\Model\RecoveryResetPassword:
    properties:
        plainPassword:
            - App\Validator\Constraints\PasswordPolicy: ~
            - NotCompromisedPassword:
                skipOnError: true

App\Form\Model\Twofactor:
    properties:
        password:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                  message: form.wrong-password

App\Form\Model\TwofactorConfirm:
    properties:
        totpSecret:
            - NotNull: ~
            - App\Validator\Constraints\TotpSecret: ~

App\Form\Model\TwofactorBackupAck:
    properties:
        ack:
            - IsTrue:
                  message: form.twofactor-backup-ack-missing
